(function () {
  "use strict";
  var defaultImages = {
    "menu-americano": "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=320&q=85",
    "menu-cafe-latte": "https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=320&q=85",
    "menu-matcha-latte": "https://images.unsplash.com/photo-1515823064-d6e0c04616a7?auto=format&fit=crop&w=320&q=85",
    "menu-earl-grey": "https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=320&q=85",
    "menu-butter-scone": "https://images.unsplash.com/photo-1551024506-0bccd828d307?auto=format&fit=crop&w=320&q=85"
  };
  var menuKey = CafeData.storageKeys.menus;
  function getMenus() { var menus = CafeUtils.storage.get(menuKey, []); if (!menus.length) { menus = CafeUtils.storage.get("cafe-app:seeded-menus", false) ? [] : CafeData.menus.map(function (menu) { var copy = Object.assign({}, menu); copy.image = menu.image || defaultImages[menu.id] || ""; return copy; }); if (menus.length) { CafeUtils.storage.set(menuKey, menus); CafeUtils.storage.set("cafe-app:seeded-menus", true); } } return menus; }
  function getCategoryName(id) { var category = CafeData.categories.find(function (item) { return item.id === id; }); return category ? category.name : id; }
  function render() { var menus = getMenus(); var term = document.getElementById("search-input").value.trim().toLowerCase(); var category = document.getElementById("category-filter").value; var availability = document.getElementById("availability-filter").value; var filtered = menus.filter(function (menu) { return (!term || menu.name.toLowerCase().includes(term)) && (category === "all" || menu.categoryId === category) && (availability === "all" || (availability === "available") === menu.isAvailable); }); document.getElementById("menu-count").textContent = menus.length; document.getElementById("available-count").textContent = menus.filter(function (menu) { return menu.isAvailable; }).length; document.getElementById("unavailable-count").textContent = menus.filter(function (menu) { return !menu.isAvailable; }).length; var list = document.getElementById("menu-list"); list.innerHTML = filtered.map(function (menu) { var status = menu.isAvailable ? '<span class="status">판매 중</span>' : '<span class="status status-off">판매 중지</span>'; return '<tr><td><div class="menu-identity"><img class="menu-photo" src="' + escapeHtml(menu.image || defaultImages[menu.id] || "") + '" alt="' + escapeHtml(menu.name) + '"><span><span class="menu-name">' + escapeHtml(menu.name) + '</span><span class="menu-description">' + escapeHtml(menu.description || "메뉴 설명이 없습니다.") + '</span></span></div></td><td class="category">' + escapeHtml(getCategoryName(menu.categoryId)) + '</td><td class="price">' + CafeUtils.formatPrice(menu.price) + '</td><td>' + status + '</td><td class="action-cell"><a class="icon-button" href="detail.html?id=' + encodeURIComponent(menu.id) + '" aria-label="' + escapeHtml(menu.name) + ' 상세 보기" title="상세 보기"><i data-lucide="arrow-up-right"></i></a><a class="icon-button" href="edit.html?id=' + encodeURIComponent(menu.id) + '" aria-label="' + escapeHtml(menu.name) + ' 수정" title="수정"><i data-lucide="pencil"></i></a><button class="icon-button delete-button" type="button" data-id="' + escapeHtml(menu.id) + '" aria-label="' + escapeHtml(menu.name) + ' 삭제" title="삭제"><i data-lucide="trash-2"></i></button></td></tr>'; }).join(""); document.getElementById("empty-state").hidden = filtered.length !== 0; if (window.lucide) { lucide.createIcons(); } }
  function escapeHtml(value) { return String(value).replace(/[&<>'"]/g, function (character) { return { "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" }[character]; }); }
  function showToast(message) { var toast = document.getElementById("toast"); toast.textContent = message; toast.classList.add("is-visible"); window.setTimeout(function () { toast.classList.remove("is-visible"); }, 2200); }
  function initialiseFilters() { var select = document.getElementById("category-filter"); CafeData.categories.forEach(function (category) { select.insertAdjacentHTML("beforeend", '<option value="' + category.id + '">' + category.name + '</option>'); }); ["search-input", "category-filter", "availability-filter"].forEach(function (id) { document.getElementById(id).addEventListener("input", render); }); document.getElementById("menu-list").addEventListener("click", function (event) { var button = event.target.closest(".delete-button"); if (!button) { return; } var menus = getMenus(); var menu = menus.find(function (item) { return item.id === button.dataset.id; }); if (menu && window.confirm("'" + menu.name + "' 메뉴를 삭제할까요?")) { CafeUtils.storage.set(menuKey, menus.filter(function (item) { return item.id !== menu.id; })); showToast("메뉴를 삭제했습니다."); render(); } }); }
  initialiseFilters(); render();
}());
